name: Build INA Sensor Binaries

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armhf, arm64]
    name: Build for ${{ matrix.arch }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up cross compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.arch }}-linux-gnu

      - name: Build binary
        run: |
          mkdir -p build/${{ matrix.arch }}
          ARCH=${{ matrix.arch }}
          if [ "$ARCH" = "armhf" ]; then
            CC=arm-linux-gnueabihf-gcc
            BIN=ina_mqtt-armhf
          else
            CC=aarch64-linux-gnu-gcc
            BIN=ina_mqtt-arm64
          fi
          $CC -O2 -Wall -o build/${{ matrix.arch }}/$BIN ina219_mqtt.c -lpaho-mqtt3c
          
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ina_mqtt-${{ matrix.arch }}
          path: build/${{ matrix.arch }}
